CREATE TABLE IF NOT EXISTS mani_analytics_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  event_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  page_path VARCHAR(160) NOT NULL,
  session_hash BINARY(32) NOT NULL,
  visitor_hash BINARY(32) NULL,
  consent_state ENUM('unknown', 'necessary', 'accepted') NOT NULL DEFAULT 'unknown',
  hero_headline_variant VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
  hero_copy_variant VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
  source VARCHAR(100) NULL,
  medium VARCHAR(100) NULL,
  campaign VARCHAR(100) NULL,
  content VARCHAR(100) NULL,
  term VARCHAR(100) NULL,
  cta_location VARCHAR(64) NULL,
  section_name VARCHAR(64) NULL,
  network VARCHAR(32) NULL,
  tone VARCHAR(24) NULL,
  control_name VARCHAR(32) NULL,
  action_name VARCHAR(32) NULL,
  error_type VARCHAR(48) NULL,
  status_code SMALLINT UNSIGNED NULL,
  metric_name VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
  metric_value DECIMAL(12,3) NULL,
  ref_present TINYINT(1) NOT NULL DEFAULT 0,
  duplicate_event TINYINT(1) NOT NULL DEFAULT 0,
  device_class ENUM('mobile', 'tablet', 'desktop', 'bot', 'unknown') NOT NULL DEFAULT 'unknown',
  browser_family VARCHAR(24) NOT NULL DEFAULT 'Other',
  os_family VARCHAR(24) NOT NULL DEFAULT 'Other',
  is_bot TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mani_analytics_event_id (event_id),
  KEY ix_mani_analytics_time_name (occurred_at, event_name),
  KEY ix_mani_analytics_session_time (session_hash, occurred_at),
  KEY ix_mani_analytics_visitor_time (visitor_hash, occurred_at),
  KEY ix_mani_analytics_headline (hero_headline_variant, event_name, occurred_at),
  KEY ix_mani_analytics_source (source, occurred_at),
  KEY ix_mani_analytics_section (section_name, occurred_at),
  KEY ix_mani_analytics_network (network, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mani_analytics_rate_limits (
  bucket_hash BINARY(32) NOT NULL,
  minute_bucket INT UNSIGNED NOT NULL,
  hits SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (bucket_hash, minute_bucket),
  KEY ix_mani_analytics_rate_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
